name: Online Competition

on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  online-competition:
    # Skip this job if running on the main repo to prevent failing CI/CD. Only run on student forks.
    if: ${{ github.repository != 'utiasDSL/lsy_drone_racing' }}

    runs-on: ubuntu-latest
    env: # Or as an environment variable
      KAGGLE_USERNAME: ${{ secrets.KaggleUsername }}
      KAGGLE_KEY: ${{ secrets.KaggleKey }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Pixi (installs pixi + caches envs) # https://github.com/marketplace/actions/setup-pixi
        uses: prefix-dev/setup-pixi@v0.9.0            # pin the action version
        with:
          pixi-version: v0.49.0                       # pin the pixi binary version (optional)
          cache: true                                 # enable caching of installed envs
          # only write new caches on main pushes (optional)
          cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
          # ensure the 'tests' environment(s) are installed
          environments: online-submission
          # don't activate env (we'll call pixi run -e test explicitly)
          activate-environment: false
          # prefer using existing lockfile if present (faster, deterministic)
          locked: true

      - name: Create online-submission times
        run: pixi run create-submission

      - name: Export with kaggle
        run: pixi run export-submission
